apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /volume1/pv/pv5
    server: 192.168.1.250
  persistentVolumeReclaimPolicy: Retain
  storageClassName: generic
